config/routes.rb
Rails.application.routes.draw do
  resources :recipe_ingredients do
    get :autocomplete_ingredient_name, :on => :collection
  end
  resources :ingredients
  resources :recipes
  resources :users
  resources :saver_recipes

  get '/search' => 'recipes#search', as: 'search'
  post '/search' => 'recipes#find'
  get '/found/:name' => 'recipes#found', as: 'found'

  get '/search_users' => 'users#search', as: 'search_users'
  post '/search_users' => 'users#find'
  get '/found_user/:first_name' => 'users#found', as: 'found_user'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'welcome#index'
    get '/signin' => 'sessions#new'
    post '/signin' => 'sessions#create'
    post '/signout' => 'sessions#destroy'

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :saver_recipes, foreign_key: "saved_recipe_id", class_name: "SaverRecipe"
  has_many :savers, through: :saver_recipes
  belongs_to :author, :class_name => "User", :foreign_key => :author_id
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_attached_file :image, styles: { medium: '300x300>', thumb: '50x50>' }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :name, presence: true
  validates :prep_time, presence: true
  validates :cook_time, presence: true
  validates :instructions, presence: true

  def times_saved
    self.savers.length
  end

  def self.published
    Recipe.all.find_all{|r| r.published}
  end

  def self.featured
    @weekly_recipes = Recipe.where(:created_at => 7.days.ago..Time.now).where(published: true)
    @weekly_recipes.sort_by{|r| r.savers.length}.reverse.first(6)
  end

  def self.top_users
    Recipe.published.sort_by{|r| r.savers.length}.reverse.map do |r|
      User.find(r.author_id)
    end.uniq.first(8)
  end

  def self.top_recipes
    Recipe.published.sort_by{|r| r.savers.length}.reverse.first(6)
  end

  def self.fast_food
    Recipe.published.sort_by{|r| r.prep_time + r.cook_time}.first(6)
  end

  def self.top_vegan
    Recipe.published.find_all{|r| r.vegan}.sort_by{|r| r.savers.length}.reverse.first(6)
  end

  def self.top_low_carb
    Recipe.published.find_all{|r| r.low_carb}.sort_by{|r| r.savers.length}.reverse.first(6)
  end

  def self.top_kosher
    Recipe.published.find_all{|r| r.kosher}.sort_by{|r| r.savers.length}.reverse.first(6)
  end

  def self.top_halal
    Recipe.published.find_all{|r| r.halal}.sort_by{|r| r.savers.length}.reverse.first(6)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @author = User.find(@recipe.author_id)
    @recipe_ingredient = RecipeIngredient.new
  end

  def new
    @recipe = Recipe.new
  end


  def create
    @recipe = Recipe.new(recipe_params)
    return render :new unless @recipe.save
    redirect_to recipe_path(@recipe)
  end

  def edit
    @recipe = Recipe.find(params[:id])
    if @recipe.author == current_user
    else
      redirect_to recipe_path(@recipe)
      flash[:notice] = "You do not have access to edit #{@recipe.author.first_name}'s recipe for #{@recipe.name}"
    end
  end


  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def search
  end

  def find
    @searched_recipes = Recipe.select(name: params[:search])
    name = params[:search].split(" ").join("_")
    redirect_to found_path(name)
  end

  def found
    name = params[:name].split("_").join(" ")
    @searched_recipes = Recipe.where(name: name)
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe_ingredients = RecipeIngredient.where(recipe_id: @recipe.id)
      @recipe_ingredients.each do |i|
        i.destroy
      end
    @recipe.destroy
    redirect_to user_path(current_user)
    flash[:notice] = "Successfully deleted #{@recipe.name}"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:image, :author_id, :name, :prep_time, :cook_time, :instructions, :source, :vegetarian, :vegan, :gluten_free, :halal, :low_carb, :kosher, :published)
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipe_form.erb
<%= form_for(@recipe) do |f| %>

  <%= f.hidden_field :author_id, :value => current_user.id %>
  <%= f.label :image, 'Add image of recipe' %><br>
  <%= f.file_field :image %>
  <%= f.label :name, 'Name Your Recipe: ' %>
  <%= f.text_field :name %><br><br>
  <%= f.label :prep_time, 'Minutes to prep your recipe: ' %>
  <%= f.number_field :prep_time %><br><br>
  <%= f.label :cook_time, 'Minutes to cook your recipe: ' %>
  <%= f.number_field :cook_time %><br><br>
  <%= f.label :instructions, 'Instructions: ' %>
  <%= f.text_area :instructions %><br><br>

  <%= f.submit %>

<% end %>

app/views/recipes/_recipe_form.html.erb
<%= form_for(@recipe) do |f| %>

  <%= f.hidden_field :author_id, :value => current_user.id %>
  <%= f.label :image, 'Add image of recipe' %><br>
  <%= f.file_field :image %><br><br>
  <%= f.label :name, 'Name Your Recipe: ' %>
  <%= f.text_field :name, required: true, class: 'validate' %><br><br>
  <%= f.label :prep_time, 'Minutes to prep your recipe: ' %>
  <%= f.number_field :prep_time, required: true, class: 'validate' %><br><br>
  <%= f.label :cook_time, 'Minutes to cook your recipe: ' %>
  <%= f.number_field :cook_time, required: true, class: 'validate' %><br><br>
  <%= f.label :instructions, 'Instructions: ' %>
  <%= f.text_area :instructions, required: true, class: 'validate', placeholder:'Please write your ingredient instructions here. You will be able to add a structured ingredients list on the following page.'%><br><br>

  <%= f.check_box :vegetarian, id:'vegetarian' %>
  <%= f.label 'Vegetarian?', id: 'vegetarian', for:'vegetarian' %><br>
  <%= f.check_box :vegan, id:'vegan' %>
  <%= f.label 'Vegan?', id: 'vegan', for:'vegan' %><br>
  <%= f.check_box :gluten_free, id:'gluten_free' %>
  <%= f.label 'Gluten-Free?', id: 'gluten_free', for:'gluten_free' %><br>
  <%= f.check_box :low_carb, id:'low_carb' %>
  <%= f.label 'Low-Carb?', id: 'low_carb', for:'low_carb' %><br>
  <%= f.check_box :halal, id:'halal' %>
  <%= f.label 'Halal?', id: 'halal', for:'halal' %><br>
  <%= f.check_box :kosher, id:'kosher' %>
  <%= f.label 'Kosher?', id: 'kosher', for:'kosher' %><br><br>
  <%= f.submit class: 'btn'%>

<% end %>

app/views/recipes/_recipe_instructions_form.html.erb
<%= form_for(@recipe) do |f| %>
  <%= f.label :instructions, 'Instructions: ' %>
  <%= f.text_area :instructions %><br><br>
<% end %>

app/views/recipes/edit.erb
<h1>Edit <%@recipe.name%></h1>
<%= render 'recipe_form' %>

app/views/recipes/found.erb
<div class="row" style="margin-bottom:20px">
   <h1>Searched Recipes</h1>
   <% @searched_recipes.each do |recipe| %>
   <div class="col s4" style="display: inline-block; margin: 20px 0;">
      <div  style="width:100%; height:200px; display: block">
         <% if recipe.image? %>
         <a href="<%=recipe_path(recipe) %>"><%=image_tag recipe.image.url(:medium), style:"width:300px;height:200px; object-fit:cover"%></a>
         <% else %>
         <img src= "<%= asset_path( 'RecipeImageDefault.png' )%>" alt="Photograph of a chocolate cupcake." style="width:300px;height:200px;object-fit:cover">
         <% end %>
      </div>
      <div  style="margin: 10px 0 0 0;">
         <%= link_to recipe.name, recipe_path(recipe), style:"color:black; font-size: 16px; " %>
      </div>
   </div>
   <% end %>
</div>

app/views/recipes/index.erb
<div class="row">
   <form class="col s12" action="/search" method="post">
      <div class="row">
         <br>
         <div class="input-field col s12">
            <i class="material-icons prefix">search</i>
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input id="icon_prefix" type="text" class="validate" name="search">
            <label for="icon_prefix">Search</label>
         </div>
      </div>
   </form>
</div>
<div >
   <h1>All Recipes</h1>
   <% Recipe.published.each do |recipe| %>
   <div class="col s4" style="display: inline-block; margin: 20px 10px;">
      <div  style="width:100%; height:200px; display: block; margin: 0 0 10px 0">
         <% if recipe.image? %>
         <a href="<%=recipe_path(recipe) %>"><%=image_tag recipe.image.url(:medium), style:"width:300px;height:200px; object-fit:cover"%></a>
         <% else %>
         <img src= "<%= asset_path( 'RecipeImageDefault.png' )%>" alt="Photograph of a chocolate cupcake." style="width:300px;height:200px;object-fit:cover">
         <% end %>
      </div>
      <div style="margin: 5px 0 0 0; display:block;">
         <%= link_to recipe.name, recipe_path(recipe), style:"color:black; font-size: 16px; " %>
      </div>
   </div>
   <% end %>
</div>

app/views/recipes/new.erb
<h1>Create New Recipe!</h1>

<%= render 'recipe_form' %>

app/views/recipes/search.erb
<div class="row">
   <form class="col s12" action="/search" method="post">
      <div class="row">
         <br><br><br><br>
         <div class="input-field col s12">
            <i class="material-icons prefix">search</i>
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input id="icon_prefix" type="text" class="validate" name="search">
            <label for="icon_prefix">Search</label>
         </div>
      </div>
   </form>
</div>

app/views/recipes/show.erb
<div class="row" style="padding-top:20px">
   <% if @recipe.image? %>
   <%= image_tag @recipe.image.url(:medium) %>
   <% end %>
</div>
<h3><%= @recipe.name %></h3>
<h5>made by <%= @author.first_name %></h5>
<% if @recipe.times_saved == 1 %>
  <h6>Saved by <%= @recipe.times_saved %> user</h6>
<% elsif @recipe.times_saved > 1 %>
  <h6>Saved by <%= @recipe.times_saved %> users</h6>
<% end %>
<div style="margin: 20px 0 0 0 ">
   <% if current_user == @recipe.author%>
   <div style="display: inline-block;">
      <% if @recipe.published == true%>
      <%= form_for @recipe do |f| %>
      <%= f.hidden_field :published, :value => false %>
      <%= f.submit "Unpublish Recipe", class:'btn'%>
      <% end %>
      <% else %>
      <%= form_for @recipe do |f| %>
      <%= f.hidden_field :published, :value => true %>
      <%= f.submit "Publish Recipe", class:'btn'%>
      <% end %>
      <% end %>
   </div>
   <%= link_to "Edit", edit_recipe_path(@recipe), class:'btn'%>
   <a class="modal-trigger waves-effect waves-light btn" href="#delete_recipe_modal">Delete</a>
   <% else %>
   <!-- THIS BUTTON IS NOT YET WORKING WORKING ON IT NOW -->
   <% if logged_in? %>
   <% if current_user.saved_recipes.include?(@recipe) %>
   <%= link_to "Unsave", saver_recipe_path(SaverRecipe.find_by(saver_id: current_user.id, saved_recipe_id: @recipe.id)), method: :delete, class:'btn' %>
   <% else %>
   <%= form_for SaverRecipe.new do |f| %>
   <%= f.hidden_field :saver_id, :value => current_user.id %>
   <%= f.hidden_field :saved_recipe_id, :value => @recipe.id %>
   <%= f.submit "Save Recipe", class:'btn'%>
   <% end %>
   <% end %>
   <% else %>
   <a class="btn" onclick="Materialize.toast('Please sign up or sign in to save this recipe.', 4000)">Save Recipe</a>
   <% end %>
   <% end %>
</div>
<br><br>
<div style="margin-bottom:50px">
   <h5>Dietary Compliance</h5>
   <% if @recipe.vegetarian == true%>
   <div class="col s2" style="display:block;">
      <div style="display:inline-block;">
         <i class="material-icons">done</i>
      </div>
      <div style="display:inline-block;">
         Vegetarian
      </div>
   </div>
   <% end %>
   <% if @recipe.vegan == true%>
   <div class="col s2" style="display:block;">
      <div style="display:inline-block;">
         <i class="material-icons">done</i>
      </div>
      <div style="display:inline-block;">
         Vegan
      </div>
   </div>
   <% end %>
   <% if @recipe.gluten_free == true%>
   <div class="col s2" style="display:block;">
      <div style="display:inline-block;">
         <i class="material-icons">done</i>
      </div>
      <div style="display:inline-block;">
         Gluten-Free
      </div>
   </div>
   <% end %>
   <% if @recipe.low_carb == true%>
   <div class="col s2" style="display:block;">
      <div style="display:inline-block;">
         <i class="material-icons">done</i>
      </div>
      <div style="display:inline-block;">
         Low-Carb
      </div>
   </div>
   <% end %>
   <% if @recipe.kosher == true%>
   <div class="col s2" style="display:block;">
      <div style="display:inline-block;">
         <i class="material-icons">done</i>
      </div>
      <div style="display:inline-block;">
         Kosher
      </div>
   </div>
   <% end %>
   <% if @recipe.halal == true%>
   <div class="col s2" style="display:block;">
      <div style="display:inline-block;">
         <i class="material-icons">done</i>
      </div>
      <div style="display:inline-block;">
         Halal
      </div>
   </div>
   <% end %>
</div>
<div style="margin-bottom:50px">
   <h5>Overview </h5>
   <p>Prep Time: <%= @recipe.prep_time %> minutes</p>
   <p>Cook Time: <%= @recipe.cook_time %> minutes</p>
   <p><strong>Total Time: <%= "#{@recipe.prep_time + @recipe.cook_time}" %> minutes</strong></p>
</div>
<div style="margin-bottom:50px">
   <h5>Ingredients: </h5>
   <% if @recipe.ingredients.count > 0 %>
   <ul>
      <% @recipe.recipe_ingredients.each do |i| %>
      <li><%= i.quantity %> <%= i.units%>  <%= i.ingredient.name %>  — <%= link_to "Remove", i, method: :delete %></li>
      <% end %>
   </ul>
   <% end %>
   <% if current_user == @recipe.author%>
   <!-- Modal Trigger -->
   <a class="modal-trigger waves-effect waves-light btn" href="#add_recipe_ingredient_modal">Add Ingredient</a>
   <!-- Modal Structure -->
   <div id="add_recipe_ingredient_modal" class="modal modal-fixed-footer">
      <div class="modal-content">
         <h4>Add Ingredient to <%=@recipe.name%></h4>
         <%= render 'recipe_ingredients/recipe_ingredient_form' %>
      </div>
   </div>
   <% end %>
</div>
<div style="margin-bottom:50px">
   <h5>Instructions: </h5>
   <%= simple_format @recipe.instructions %>
</div>
<br>
<!-- MODALS -->
<div id="delete_recipe_modal" class="modal modal-fixed-footer">
   <div class="modal-content">
      <h4>Are you sure you want to delete <%=@recipe.name%>?</h4>
      <% if @recipe.savers.count == 1 %>
      <p>
         <%= @recipe.savers.count %> other chef has saved this recipe and will miss it dearly!
      </p>
      <% elsif @recipe.savers.count > 1 %>
      <p>
         <%= @recipe.savers.count %> other chefs have saved this recipe and will miss it dearly!
      </p>
      <% else%>
      <p>
         Other chefs will miss out on your knowledge!
      </p>
      <% end %>
   </div>
   <div class="modal-footer">
      <div>
         <%= link_to "Yes, Delete This Recipe", @recipe, method: :delete, class:'btn' %>
      </div>
      <div>
         <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">No, Don't Delete</a>
      </div>
   </div>
</div>