config/routes.rb
Rails.application.routes.draw do
  resources :recipe_ingredients do
    get :autocomplete_ingredient_name, :on => :collection
  end
  resources :ingredients
  resources :recipes
  resources :users
  resources :saver_recipes

  get '/search' => 'recipes#search', as: 'search'
  post '/search' => 'recipes#find'
  get '/found/:name' => 'recipes#found', as: 'found'

  get '/search_users' => 'users#search', as: 'search_users'
  post '/search_users' => 'users#find'
  get '/found_user/:first_name' => 'users#found', as: 'found_user'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'welcome#index'
    get '/signin' => 'sessions#new'
    post '/signin' => 'sessions#create'
    post '/signout' => 'sessions#destroy'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :saver_recipes, foreign_key: "saver_id", class_name: "SaverRecipe"
  has_many :saved_recipes, through: :saver_recipes
  has_many :recipes, foreign_key: "author_id", class_name: "Recipe"
  has_attached_file :image, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: :link_to_image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_secure_password

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :first_name, presence: true

  def name
    "#{first_name} #{last_name}"
  end

  def link_to_image
    "https://lh3.googleusercontent.com/H9yAIsZYqbIOh_E1ON90chVhO6SYSD6ucV-XirZXkMFDqLRjGoztobaxx1XS9CB4lfg=w300"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticated, except: [:new, :create, :index, :show, :find, :found, :search]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])

  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(@user)
      flash[:notice] = "You do not have access to edit #{@user.name}"
    end
  end

  def update
    # binding.pry
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def search
  end

  def find
    @searched_users = User.select(first_name: params[:search])
    name = params[:search].split(" ").join("_")
    redirect_to found_user_path(name)
  end

  def found
    name = params[:first_name].split("_").join(" ")
    @searched_users = User.where(first_name: name)
  end

  def delete
    current_user.destroy
    redirect_to root_path
  end

private
  def user_params
    params.require(:user).permit(:image, :first_name, :last_name, :email, :password, :password_confirmation, :location)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_form.html.erb
<%=form_for(@user) do |f| %>
  <%= f.label :image, 'Profile Picture' %><br>
  <%= f.file_field :image  %><br><br>
  <%= f.label :first_name, 'First Name *'%> <br>
  <%= f.text_field(:first_name, placeholder: "First Name", required: true, class: 'validate')%> <br><br>
  <%= f.label :last_name%> <br>
  <%= f.text_field(:last_name, placeholder: "Last Name")%> <br><br>
  <%= f.label :email, 'Email *'%> <br>
  <%= f.text_field(:email, placeholder: "Email", required: true, class: 'validate')%> <br><br>
  <%= f.label :password, 'Password *'%> <br>
  <%= f.password_field(:password, placeholder: "Password", required: true, class: 'validate')%><br><br>
  <%= f.label :password_confirmation, 'Password Confirmation *'%> <br>
  <%= f.password_field(:password_confirmation, placeholder: "Confirm Password", class: 'validate')%><br><br>

  <%= f.label :location%> <br>
  <%= f.text_field(:location, placeholder: "City, State")%> <br><br>

  <%= f.submit class: 'btn'%>
<%end%>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render "user_form" %>

app/views/users/found.erb
<div class="row" style="margin-bottom:20px">
   <h1>Searched Users</h1>
   <% @searched_users.each do |user| %>
   <div class="col s3" style="display: inline-block; margin: 20px 0;">
      <div  style="width:120px; height:100px; display: block;">
         <% if user.image? %>
         <a href="<%=user_path(user) %>"><%=image_tag user.image.url(:thumb), style:"width:100px;height:100px; object-fit:cover; border-radius: 50%"%></a>
         <% else %>
         <a href="<%=user_path(user) %>"><img src= "<%= asset_path( 'ProfileImageDefault.png' )%>" alt="Photograph of a chocolate cupcake." style="width:100px;height:100px;"></a>
         <% end %>
      </div>
      <div style="margin: 10px 0 0 0;display:block; width:100px;  text-align: center;">
         <%= link_to user.first_name, user_path(user), style:"color:black; font-size: 16px; " %>
      </div>
   </div>
   <% end %>
</div>

app/views/users/index.html.erb
<div class="row">
    <form class="col s12" action="/search_users" method="post">
      <div class="row">
        <br>
        <div class="input-field col s12">
          <i class="material-icons prefix">search</i>
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input id="icon_prefix" type="text" class="validate" name="search">
          <label for="icon_prefix">Search</label>
        </div>
      </div>
    </form>
  </div>


<div class="row">
<h1>All Users</h1>
   <% User.all.each do |user| %>
   <div class="col s3" style="display: inline-block; margin: 20px 0;">
     <div  style="width:120px; height:100px; display: block;">
        <% if user.image? %>
        <a href="<%=user_path(user) %>"><%=image_tag user.image.url(:thumb), style:"width:100px;height:100px; object-fit:cover; border-radius: 50%"%></a>
        <% else %>
          <a href="<%=user_path(user) %>"><img src= "<%= asset_path( 'ProfileImageDefault.png' )%>" alt="Photograph of a chocolate cupcake." style="width:100px;height:100px;"></a>
        <% end %>
     </div>
     <div style="margin: 10px 0 0 0;display:block; width:100px;  text-align: center;">
      <%= link_to user.first_name, user_path(user), style:"color:black; font-size: 16px; " %>
     </div>
 </div>
   <% end %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render "user_form" %>

app/views/users/show.html.erb
<h5>USER PROFILE</h5>
<div style="height:150px; width: 150px;">
   <% if @user.image? %>
   <%= image_tag @user.image.url(:medium), style:"width:150px; height:150px; object-fit:cover; border-radius: 50%" %>
   <% else %>
   <img src= "<%= asset_path('ProfileImageDefault.png')%>" alt="profile image default" style="width:150px;height:150px; object-fit:cover; ">
   <% end %>
</div>
<div>
   <h3> <%= @user.name %></h3>
</div>
<div>
   <% if @user == current_user  %>
   <p>
      <%= link_to "Edit Profile", edit_user_path, class:'btn' %> <%= link_to "Add New Recipe", new_recipe_path, class:'btn' %>
   </p>
   <% end %>
</div>
<div style="margin-top:50px">
   <h5 > Account Details </h5>
   <ul>
      <li>
         Email: <%= @user.email %>
      </li>
      <li>
         Location: <%= @user.location %>
      </li>
   </ul>
</div>
<div style="margin-top:50px">
   <h5> Authored Recipes </h5>
   <% if @user.recipes.count > 0%>
   <% @user.recipes.each do |recipe|%>
   <div class="col s4" style="display: inline-block; margin: 20px 10px 20px 10px;">
      <div  style="width:100%; height:200px; display: block">
         <% if recipe.image? %>
         <a href="<%=recipe_path(recipe) %>"><%=image_tag recipe.image.url(:medium), style:"width:300px;height:200px; object-fit:cover"%></a>
         <% else %>
         <img src= "<%= asset_path( 'RecipeImageDefault.png' )%>" alt="Photograph of a chocolate cupcake." style="width:300px;height:200px;object-fit:cover">
         <% end %>
      </div>
      <div  style="margin: 10px 0 0 0;">
         <%= link_to recipe.name, recipe_path(recipe), style:"color:black; font-size: 16px; " %>
      </div>
   </div>
   <% end %>
   <% else %>
   <p>
      <%= @user.first_name%> has not yet authored any recipes
   </p>
   <% end %>
</div>
<div style="margin-top:50px">
   <h5> Saved Recipes </h5>
   <% if @user.saved_recipes.count > 0%>
   <% @user.saved_recipes.each do |recipe|%>
   <div class="col s4" style="display: inline-block; margin: 20px 10px 20px 10px;">
      <div  style="width:100%; height:200px; display: block">
         <% if recipe.image? %>
         <a href="<%=recipe_path(recipe) %>"><%=image_tag recipe.image.url(:medium), style:"width:300px;height:200px; object-fit:cover"%></a>
         <% else %>
         <img src= "<%= asset_path( 'RecipeImageDefault.png' )%>" alt="Photograph of a chocolate cupcake." style="width:300px;height:200px;object-fit:cover">
         <% end %>
      </div>
      <div  style="margin: 10px 0 0 0;">
         <%= link_to recipe.name, recipe_path(recipe), style:"color:black; font-size: 16px; " %>
      </div>
   </div>
   <% end %>
   <% else %>
   <p>
      <%= @user.first_name%> has not yet saved any recipes
   </p>
   <% end %>
</div>