config/routes.rb
Rails.application.routes.draw do
  resources :recipe_ingredients do
    get :autocomplete_ingredient_name, :on => :collection
  end
  resources :ingredients
  resources :recipes
  resources :users
  resources :saver_recipes

  get '/search' => 'recipes#search', as: 'search'
  post '/search' => 'recipes#find'
  get '/found/:name' => 'recipes#found', as: 'found'

  get '/search_users' => 'users#search', as: 'search_users'
  post '/search_users' => 'users#find'
  get '/found_user/:first_name' => 'users#found', as: 'found_user'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'welcome#index'
    get '/signin' => 'sessions#new'
    post '/signin' => 'sessions#create'
    post '/signout' => 'sessions#destroy'

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
      if @ingredient.save
        redirect_to ingredient_path(@ingredient)
      else
        render :new
      end
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update(ingredient_params)
      redirect_to ingredient_path(@ingredient)
    else
      render :edit
    end
  end

  def destroy
  end

  private
  def ingredient_params
    params.require(:ingredient).permit(:name, :category, :food_group)
  end





end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/index.html.erb
<h1> Ingredients List</h1>
  <table cellspacing='20'>
    <tr>
      <th>Name</th>
      <th>&nbsp;</th>
      <th>Category</th>
      <th>&nbsp;</th>
      <th>Food Group</th>
    </tr>
    <% @ingredients.each do |ingredient| %>
    <tr>
      <td> <%= ingredient.name %> </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td> <%= ingredient.category %> </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td> <%= ingredient.food_group %> </td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td> <%= link_to "#{ingredient.name}", ingredient_path(ingredient) %> </ bbtd>
    </tr>
    <% end %>
  </table>
<br>
  <%= link_to "Add New Ingredient", new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1> New Ingredient </h1>

<%= form_for(@ingredient) do |t| %>
<%= t.text_field :name, placeholder: "Name" %><br>
<%= t.text_field :food_group, placeholder: "Food Group" %><br>

<%= t.submit "Create Ingredient" %>
<% end %>

app/views/ingredients/show.html.erb
<h1> <%= @ingredient.name %> </h1>
<p>Food Group: <%= @ingredient.food_group  %> </p>

<%= link_to "Edit", edit_ingredient_path(@ingredient) %><br>